FROM python:3.9-alpine

RUN apk update && apk add build-base

RUN pip install --upgrade pip && \
    pip install \
    faker \
    flask \
    flask-restful \
    jsonschema \
    pexpect \
    pytest \
    pytest-repeat \
    pytest-xdist \
    requests \
    sqlalchemy

WORKDIR /app

CMD /bin/sh
